In [3]:
import os
import sys

# Move one level up from Notebook to the project root
project_root = os.path.abspath("..")

if project_root not in sys.path:
    sys.path.insert(0, project_root)

In [4]:
import librosa
import numpy as np
import pandas as pd

from tqdm import tqdm

import parselmouth
from Features.pitch import extract_pitch_features
from Features.loudness import extract_loudness_features
from Features.spectral import extract_spectral_features

In [5]:
emotion_map = {
    "01": "neutral",
    "02": "calm",
    "03": "happy",
    "04": "sad",
    "05": "angry",
    "06": "fearful",
    "07": "disgust",
    "08": "surprised"
}

In [6]:
dataset_path = r"F:\PhD\PhD_Project\Dataset"

sample_file = None

for root, dirs, files in os.walk(dataset_path):

    for file in files:

        if file.endswith(".wav"):

            sample_file = os.path.join(
                root,
                file
            )

            break

    if sample_file:
        break

sample_file

'F:\\PhD\\PhD_Project\\Dataset\\Actor_01\\03-01-01-01-01-01-01.wav'

In [7]:
features = extract_pitch_features(
    sample_file
)

features

[np.float64(111.84901197907737),
 np.float64(157.81439077794457),
 np.float64(80.76557238569704),
 np.float64(17.726207315694698),
 np.float64(77.04881839224753)]

In [8]:
pitch_data = []

for root, dirs, files in os.walk(dataset_path):

    for file in tqdm(files):

        if file.endswith(".wav"):

            file_path = os.path.join(
                root,
                file
            )

            emotion_id = file.split("-")[2]

            emotion = emotion_map[
                emotion_id
            ]

            features = extract_pitch_features(
                file_path
            )

            pitch_data.append(

                [
                    file
                ]

                +

                features

                +

                [
                    emotion
                ]

            )

0it [00:00, ?it/s]
  0%|          | 0/60 [00:00<?, ?it/s]

100%|██████████| 60/60 [00:01<00:00, 49.06it/s]
100%|██████████| 60/60 [00:01<00:00, 47.42it/s]
100%|██████████| 60/60 [00:01<00:00, 52.10it/s]
100%|██████████| 60/60 [00:01<00:00, 59.67it/s]
100%|██████████| 60/60 [00:01<00:00, 58.20it/s]
100%|██████████| 60/60 [00:00<00:00, 64.38it/s]
100%|██████████| 60/60 [00:00<00:00, 60.03it/s]
100%|██████████| 60/60 [00:01<00:00, 56.63it/s]
100%|██████████| 60/60 [00:00<00:00, 62.70it/s]
100%|██████████| 60/60 [00:00<00:00, 65.37it/s]
100%|██████████| 60/60 [00:00<00:00, 67.68it/s]
100%|██████████| 60/60 [00:00<00:00, 70.79it/s]
100%|██████████| 60/60 [00:00<00:00, 68.75it/s]
100%|██████████| 60/60 [00:00<00:00, 82.83it/s]
100%|██████████| 60/60 [00:00<00:00, 70.06it/s]
100%|██████████| 60/60 [00:00<00:00, 75.43it/s]
100%|██████████| 60/60 [00:00<00:00, 67.13it/s]
100%|██████████| 60/60 [00:00<00:00, 86.07it/s]
100%|██████████| 60/60 [00:00<00:00, 66.06it/s]
100%|██████████| 60/60 [00:00<00:00, 86.18it/s]
100%|██████████| 60/60 [00:00<00:00, 69.28it/s]
100%|██████████| 60/60 [00:00<00:00, 72.32it/s]
100%|██████████| 60/60 [00:00<00:00, 84.49it/s]
100%|██████████| 60/60 [00:00<00:00, 83.28it/s]
0it [00:00, ?it/s]
100%|██████████| 60/60 [00:00<00:00, 86.57it/s]
100%|██████████| 60/60 [00:00<00:00, 88.50it/s]
100%|██████████| 60/60 [00:00<00:00, 86.02it/s]
100%|██████████| 60/60 [00:00<00:00, 88.16it/s]
100%|██████████| 60/60 [00:00<00:00, 68.74it/s]
100%|██████████| 60/60 [00:00<00:00, 86.44it/s]
100%|██████████| 60/60 [00:00<00:00, 85.06it/s]
100%|██████████| 60/60 [00:00<00:00, 76.02it/s]
100%|██████████| 60/60 [00:00<00:00, 87.71it/s]
100%|██████████| 60/60 [00:00<00:00, 81.67it/s]
100%|██████████| 60/60 [00:00<00:00, 79.82it/s]
100%|██████████| 60/60 [00:00<00:00, 86.79it/s]
100%|██████████| 60/60 [00:00<00:00, 83.33it/s]
100%|██████████| 60/60 [00:00<00:00, 98.90it/s]
100%|██████████| 60/60 [00:00<00:00, 86.44it/s]
100%|██████████| 60/60 [00:00<00:00, 90.34it/s]
100%|██████████| 60/60 [00:00<00:00, 75.09it/s]
100%|██████████| 60/60 [00:00<00:00, 102.78it/s]
100%|██████████| 60/60 [00:00<00:00, 77.47it/s]
100%|██████████| 60/60 [00:00<00:00, 99.54it/s]
100%|██████████| 60/60 [00:00<00:00, 68.59it/s]
100%|██████████| 60/60 [00:00<00:00, 78.53it/s]
100%|██████████| 60/60 [00:00<00:00, 87.83it/s]
100%|██████████| 60/60 [00:00<00:00, 75.96it/s]

In [9]:
columns = [

    "file",

    "mean_pitch",

    "max_pitch",

    "min_pitch",

    "std_pitch",

    "pitch_range",

    "emotion"

]

pitch_df = pd.DataFrame(
    pitch_data,
    columns=columns
)

pitch_df.head()

,file,mean_pitch,max_pitch,min_pitch,std_pitch,pitch_range,emotion
0,03-01-01-01-01-01-01.wav,111.849012,157.814391,80.765572,17.726207,77.048818,neutral
1,03-01-01-01-01-02-01.wav,117.245068,163.597137,84.473408,18.327280,79.123729,neutral
2,03-01-01-01-02-01-01.wav,112.329468,146.774651,86.827031,15.661057,59.947620,neutral
3,03-01-01-01-02-02-01.wav,111.169592,146.511514,84.942462,16.161782,61.569053,neutral
4,03-01-02-01-01-01-01.wav,117.901185,157.434160,83.595426,19.596982,73.838734,calm

In [10]:
output_path = r"F:\PhD\PhD_Project\Outputs\pitch_features.csv"

pitch_df.to_csv(
    output_path,
    index=False
)

print(
    "Saved Successfully"
)

Saved Successfully

# Loudness Feature Extraction

In [11]:
extract_loudness_features(
    sample_file
)

[np.float32(0.002256089),
 np.float32(0.012584829),
 np.float32(7.0248973e-07),
 np.float32(0.0032887615),
 np.float32(0.012584127)]

In [12]:
loudness_data = []

for root, dirs, files in os.walk(dataset_path):

    for file in tqdm(files):

        if file.endswith(".wav"):

            file_path = os.path.join(
                root,
                file
            )

            emotion_id = file.split("-")[2]

            emotion = emotion_map[
                emotion_id
            ]

            features = extract_loudness_features(
                file_path
            )

            loudness_data.append(

                [
                    file
                ]

                +

                features

                +

                [
                    emotion
                ]

            )

0it [00:00, ?it/s]
100%|██████████| 60/60 [00:00<00:00, 235.68it/s]
100%|██████████| 60/60 [00:00<00:00, 255.89it/s]
100%|██████████| 60/60 [00:00<00:00, 240.26it/s]
100%|██████████| 60/60 [00:00<00:00, 250.43it/s]
100%|██████████| 60/60 [00:00<00:00, 220.84it/s]
100%|██████████| 60/60 [00:00<00:00, 210.22it/s]
100%|██████████| 60/60 [00:00<00:00, 211.24it/s]
100%|██████████| 60/60 [00:00<00:00, 222.05it/s]
100%|██████████| 60/60 [00:00<00:00, 246.89it/s]
100%|██████████| 60/60 [00:00<00:00, 247.00it/s]
100%|██████████| 60/60 [00:00<00:00, 241.40it/s]
100%|██████████| 60/60 [00:00<00:00, 236.99it/s]
100%|██████████| 60/60 [00:00<00:00, 229.68it/s]
100%|██████████| 60/60 [00:00<00:00, 223.07it/s]
100%|██████████| 60/60 [00:00<00:00, 243.60it/s]
100%|██████████| 60/60 [00:00<00:00, 223.44it/s]
100%|██████████| 60/60 [00:00<00:00, 218.10it/s]
100%|██████████| 60/60 [00:00<00:00, 218.96it/s]
100%|██████████| 60/60 [00:00<00:00, 219.74it/s]
100%|██████████| 60/60 [00:00<00:00, 209.35it/s]
100%|██████████| 60/60 [00:00<00:00, 228.95it/s]
100%|██████████| 60/60 [00:00<00:00, 240.61it/s]
100%|██████████| 60/60 [00:00<00:00, 232.59it/s]
100%|██████████| 60/60 [00:00<00:00, 203.77it/s]
0it [00:00, ?it/s]
100%|██████████| 60/60 [00:00<00:00, 227.29it/s]
100%|██████████| 60/60 [00:00<00:00, 223.85it/s]
100%|██████████| 60/60 [00:00<00:00, 199.78it/s]
100%|██████████| 60/60 [00:00<00:00, 212.19it/s]
100%|██████████| 60/60 [00:00<00:00, 197.22it/s]
100%|██████████| 60/60 [00:00<00:00, 210.55it/s]
100%|██████████| 60/60 [00:00<00:00, 200.43it/s]
100%|██████████| 60/60 [00:00<00:00, 217.01it/s]
100%|██████████| 60/60 [00:00<00:00, 185.33it/s]
100%|██████████| 60/60 [00:00<00:00, 222.17it/s]
100%|██████████| 60/60 [00:00<00:00, 233.37it/s]
100%|██████████| 60/60 [00:00<00:00, 227.53it/s]
100%|██████████| 60/60 [00:00<00:00, 252.78it/s]
100%|██████████| 60/60 [00:00<00:00, 249.41it/s]
100%|██████████| 60/60 [00:00<00:00, 230.91it/s]
100%|██████████| 60/60 [00:00<00:00, 263.68it/s]
100%|██████████| 60/60 [00:00<00:00, 232.77it/s]
100%|██████████| 60/60 [00:00<00:00, 256.12it/s]
100%|██████████| 60/60 [00:00<00:00, 248.40it/s]
100%|██████████| 60/60 [00:00<00:00, 235.94it/s]
100%|██████████| 60/60 [00:00<00:00, 240.08it/s]
100%|██████████| 60/60 [00:00<00:00, 234.27it/s]
100%|██████████| 60/60 [00:00<00:00, 243.64it/s]
100%|██████████| 60/60 [00:00<00:00, 233.65it/s]

In [13]:
columns = [

    "file",

    "mean_loudness",

    "max_loudness",

    "min_loudness",

    "std_loudness",

    "loudness_range",

    "emotion"

]

loudness_df = pd.DataFrame(
    loudness_data,
    columns=columns
)

loudness_df.head()

,file,mean_loudness,max_loudness,min_loudness,std_loudness,loudness_range,emotion
0,03-01-01-01-01-01-01.wav,0.002256,0.012585,7.024897e-07,0.003289,0.012584,neutral
1,03-01-01-01-01-02-01.wav,0.002419,0.013047,1.374355e-06,0.003526,0.013045,neutral
2,03-01-01-01-02-01-01.wav,0.002809,0.017971,1.693580e-06,0.004224,0.017970,neutral
3,03-01-01-01-02-02-01.wav,0.002617,0.018385,1.377273e-06,0.004103,0.018383,neutral
4,03-01-02-01-01-01-01.wav,0.001653,0.010988,9.366694e-07,0.002440,0.010987,calm

In [14]:
print(
    "Total Rows:",
    len(loudness_df)
)

Total Rows: 2880

In [15]:
output_path = r"F:\PhD\PhD_Project\Outputs\loudness_features.csv"

loudness_df.to_csv(
    output_path,
    index=False
)

print(
    "Loudness Features Saved"
)

Loudness Features Saved

In [16]:
loudness_df.groupby(
    "emotion"
)[
    "mean_loudness"
].mean()

emotion
angry        0.026401
calm         0.002666
disgust      0.006366
fearful      0.016032
happy        0.012380
neutral      0.003175
sad          0.005146
surprised    0.008371
Name: mean_loudness, dtype: float32

In [17]:
loudness_df.groupby("emotion")["mean_loudness"].mean()

emotion
angry        0.026401
calm         0.002666
disgust      0.006366
fearful      0.016032
happy        0.012380
neutral      0.003175
sad          0.005146
surprised    0.008371
Name: mean_loudness, dtype: float32

# Spectral Feature Extraction

In [18]:
extract_spectral_features(sample_file)

[np.float64(3470.9376892500345),
 np.float64(2628.243580309864),
 np.float64(6330.3852641499125),
 np.float64(19.423303049631183),
 np.float32(0.21591613)]

In [19]:
spectral_data = []

for root, dirs, files in os.walk(dataset_path):

    for file in tqdm(files):

        if file.endswith(".wav"):

            file_path = os.path.join(root, file)

            emotion_id = file.split("-")[2]
            emotion = emotion_map[emotion_id]

            features = extract_spectral_features(file_path)

            spectral_data.append(
                [file] + features + [emotion]
            )

0it [00:00, ?it/s]
100%|██████████| 60/60 [00:03<00:00, 19.12it/s]
100%|██████████| 60/60 [00:02<00:00, 20.78it/s]
100%|██████████| 60/60 [00:03<00:00, 18.20it/s]
100%|██████████| 60/60 [00:03<00:00, 19.15it/s]
100%|██████████| 60/60 [00:02<00:00, 20.01it/s]
100%|██████████| 60/60 [00:02<00:00, 20.28it/s]
100%|██████████| 60/60 [00:03<00:00, 19.41it/s]
100%|██████████| 60/60 [00:02<00:00, 21.63it/s]
100%|██████████| 60/60 [00:02<00:00, 20.16it/s]
100%|██████████| 60/60 [00:03<00:00, 18.16it/s]
100%|██████████| 60/60 [00:02<00:00, 21.39it/s]
100%|██████████| 60/60 [00:03<00:00, 19.44it/s]
100%|██████████| 60/60 [00:02<00:00, 24.61it/s]
100%|██████████| 60/60 [00:02<00:00, 21.95it/s]
100%|██████████| 60/60 [00:02<00:00, 24.71it/s]
100%|██████████| 60/60 [00:02<00:00, 20.18it/s]
100%|██████████| 60/60 [00:02<00:00, 20.80it/s]
100%|██████████| 60/60 [00:02<00:00, 20.28it/s]
100%|██████████| 60/60 [00:03<00:00, 19.86it/s]
100%|██████████| 60/60 [00:02<00:00, 20.81it/s]
100%|██████████| 60/60 [00:03<00:00, 19.61it/s]
100%|██████████| 60/60 [00:02<00:00, 20.34it/s]
100%|██████████| 60/60 [00:02<00:00, 22.74it/s]
100%|██████████| 60/60 [00:02<00:00, 20.63it/s]
0it [00:00, ?it/s]
100%|██████████| 60/60 [00:02<00:00, 20.29it/s]
100%|██████████| 60/60 [00:02<00:00, 21.08it/s]
100%|██████████| 60/60 [00:02<00:00, 22.01it/s]
100%|██████████| 60/60 [00:02<00:00, 21.76it/s]
100%|██████████| 60/60 [00:02<00:00, 20.55it/s]
100%|██████████| 60/60 [00:02<00:00, 20.58it/s]
100%|██████████| 60/60 [00:02<00:00, 22.77it/s]
100%|██████████| 60/60 [00:02<00:00, 21.97it/s]
100%|██████████| 60/60 [00:02<00:00, 21.69it/s]
100%|██████████| 60/60 [00:02<00:00, 20.14it/s]
100%|██████████| 60/60 [00:02<00:00, 22.39it/s]
100%|██████████| 60/60 [00:02<00:00, 20.57it/s]
100%|██████████| 60/60 [00:02<00:00, 22.35it/s]
100%|██████████| 60/60 [00:02<00:00, 22.31it/s]
100%|██████████| 60/60 [00:02<00:00, 23.75it/s]
100%|██████████| 60/60 [00:02<00:00, 21.76it/s]
100%|██████████| 60/60 [00:02<00:00, 23.19it/s]
100%|██████████| 60/60 [00:02<00:00, 22.46it/s]
100%|██████████| 60/60 [00:02<00:00, 21.01it/s]
100%|██████████| 60/60 [00:02<00:00, 21.02it/s]
100%|██████████| 60/60 [00:03<00:00, 19.51it/s]
100%|██████████| 60/60 [00:02<00:00, 21.51it/s]
100%|██████████| 60/60 [00:02<00:00, 22.89it/s]
100%|██████████| 60/60 [00:02<00:00, 21.00it/s]

In [20]:
columns = [

    "file",

    "spectral_centroid",

    "spectral_bandwidth",

    "spectral_rolloff",

    "spectral_contrast",

    "spectral_flatness",

    "emotion"

]

spectral_df = pd.DataFrame(
    spectral_data,
    columns=columns
)

spectral_df.head()

,file,spectral_centroid,spectral_bandwidth,spectral_rolloff,spectral_contrast,spectral_flatness,emotion
0,03-01-01-01-01-01-01.wav,3470.937689,2628.243580,6330.385264,19.423303,0.215916,neutral
1,03-01-01-01-01-02-01.wav,3264.835349,2675.836121,6237.152100,19.883596,0.169367,neutral
2,03-01-01-01-02-01-01.wav,3233.896121,2633.346044,6180.487450,19.583326,0.171418,neutral
3,03-01-01-01-02-02-01.wav,3114.655307,2675.402307,6165.490455,19.796049,0.152266,neutral
4,03-01-02-01-01-01-01.wav,3226.498012,2629.698536,6070.041073,19.323400,0.194481,calm

In [21]:
output_path = r"F:\PhD\PhD_Project\Outputs\spectral_features.csv"

spectral_df.to_csv(
    output_path,
    index=False
)

print("Spectral Features Saved Successfully!")

Spectral Features Saved Successfully!